
#define UART_REGISTERS_MEMORY_ADDRESS (*(unsigned char *)0x40008000)

int main(void) {

  UART_REGISTERS_MEMORY_ADDRESS = 'T';
  UART_REGISTERS_MEMORY_ADDRESS = 'e';
  UART_REGISTERS_MEMORY_ADDRESS = 's';
  UART_REGISTERS_MEMORY_ADDRESS = 't';

  asm volatile ("ecall");
}